name = "LOBPCGEigensolver"
uuid = "87a0849e-8492-4fcc-8734-ba6a5d902784"
authors = ["Michael F. Herbst <info@michael-herbst.com>", "Antoine Levitt <antoine.levitt@inria.fr>"]
version = "0.1.2"

[deps]
GPUArraysCore = "46192b85-c4d5-4398-a991-12ede77f4527"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NVTX = "5da4648a-3479-48b8-97b9-01cb529c0a1f"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[weakdeps]
AMDGPU = "21141c5a-9bdb-4563-92ae-f87d6854732e"

[extensions]
LOBPCGEigensolverAMDGPUExt = "AMDGPU"

[compat]
AMDGPU = "1.2.3, 2"
GPUArraysCore = "0.1, 0.2"
LinearAlgebra = "1"
NVTX = "1"
Printf = "1"
Random = "1"
TimerOutputs = "0.5.29"
julia = "1.10"

[extras]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[targets]
test = ["Test", "LinearAlgebra", "Random", "TimerOutputs"]
